name: Deploy HTML Files to AppService - CMST385

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy project1 to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'CMST385-jdonkor2'             
          slot-name: 'production'
          publish-profile: ${{ secrets.APPSERVICECMST385 }}  
          package: ./project1                        
