name: Deploy HTML Files to AppService - CMST385

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy project1 to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          # MUST match the Site/App name in your Publish Settings exactly
          app-name: 'CMST385-jdonkor2'
          slot-name: 'production'
          # MUST match your repo secret name in Settings → Secrets and variables → Actions
          publish-profile: ${{ secrets.AppServiceCMST385 }}
          # Deploy only the project1 folder as the web root
          package: ./project1
