name: Deploy site to Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy using publish profile
        uses: azure/webapps-deploy@v3
        with:
          app-name: CMST385-UMGC-jdonkor2
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .
